name: if condition with functions
on:
  push:
    branches:
      - main
      - dev
      - feature/**
jobs:
  job_build:
    runs-on: ubuntu-latest
    if: github.actor == 'reddyharinath' && startsWith(github.ref_name,'feature')
    steps:
      - name: build while pushing code to branch starts with feature
        run: echo "build job got triggered by ${{github.actor}} and on branch ${{github.ref_name}}"
  job_dev_deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev' && github.actor == 'reddyharinath'
    steps:
      - name: dev deployment step
        run: echo "dev deployment job got triggered by ${{github.actor}} and on branch ${{github.ref_name}}"
  job_prod_deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' && github.actor == 'reddyharinath'
    steps:
      - name: prod deployment step
        run: echo "prod deployment job got triggered by ${{github.actor}} and on branch ${{github.ref_name}}"
  job_success_notification:
    needs: ['job_build','job_dev_deploy','job_prod_deploy']
    if: always() && !failure()
    runs-on: ubuntu-latest
    steps:
      - name: send success notification to team
        run: echo "deployment job got triggered by ${{github.actor}} and on branch ${{github.ref_name}} and it is success"
  job_failure_notification:
    needs: ['job_build','job_dev_deploy','job_prod_deploy']
    if: failure()
    runs-on: ubtuntu-latest
    steps:
      - name: send failure notification to the team
        run: echo "deployment job got triggered by ${{github.actor}} and on branch ${{github.ref_name}} and it is failed"
  
