name: sample hello world workflow
on: workflow_dispatch
jobs:
  hello world job:
    runs-on: ubuntu-latest
    steps:
      - name: hello world job step
        run: echo "hello world workflow job step"
