name: secrests examples
on: workflow_dispatch
jobs:
  job_secrets_example:
    runs-on: ubuntu-latest
    steps:
      - name: secrets example steps
        run: echo " the secret name is ${{ secrets.GITHUB_TOKEN}}"
